package frames;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.control.CheckBox;

import javafx.scene.control.DatePicker;

public class addmissionController2 {
	@FXML
	private CheckBox partbox;
	@FXML
	private CheckBox flexbox;
	@FXML
	private TextField titletf;
	@FXML
	private ComboBox fieldcb;
	@FXML
	private DatePicker startdate;
	@FXML
	private DatePicker enddate;
	@FXML
	private TextField pricetf;
	@FXML
	private ComboBox skillscb;
	@FXML
	private TextField descriptiontf;
	@FXML
	private CheckBox localbox;
	@FXML
	private Button AddBTN;
	@FXML
	private Button sk;
	@FXML
	private Label skills;

	// Event Listener on Button[#AddBTN].onAction
	@FXML
	public void ADDMISSION(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#sk].onAction
	@FXML
	public void skills(ActionEvent event) {
		// TODO Autogenerated
	}
}
